- name: Build Docker Image
  hosts: dockerservers
  gather_facts: false
  remote_user: root
  tasks:
    - name: Building Docker Image
      docker_image:
        name: admin-jenkins:latest  # Docker image name
        source: build
        build:
          path: /root/admin-jenkins  # Path ที่เก็บไฟล์ source code
        state: present
        force_source: true
